### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by zuphilip**
Add German translation

### CODE REVIEW

**Comment by zuphilip** [comment]
Ping @wfyson

**Comment by wfyson** [comment]
Apologies for the delay in merging this - I'll try and get the Bazaar version updated as soon as possible.

**Comment by zuphilip** [comment]
Sure, give me a minute or so... I just see two new phrases.

**Comment by zuphilip** [comment]
@wfyson Done, see PR #9.

**Pull request merged**
